"use client";

import Sidebar from "@/components/Sidebar";
import { insights } from "@/data";
import { Lightbulb, TrendingUp, TrendingDown, AlertTriangle, Link2, Sparkles } from "lucide-react";

const typeConfig: Record<string, { icon: React.ReactNode; class: string; label: string }> = {
  "trend-up": { icon: <TrendingUp size={14} className="text-[#22C55E]" />, class: "trend-up", label: "Trend" },
  "trend-down": { icon: <TrendingDown size={14} className="text-[#EF4444]" />, class: "trend-down", label: "Decline" },
  anomaly: { icon: <AlertTriangle size={14} className="text-[#F59E0B]" />, class: "anomaly", label: "Anomaly" },
  correlation: { icon: <Link2 size={14} className="text-[#8B5CF6]" />, class: "correlation", label: "Correlation" },
};

export default function InsightsPage() {
  return (
    <div className="flex min-h-screen">
      <div className="bg-orb w-96 h-96 bg-[#F59E0B] top-[-10%] left-[20%]" />
      <Sidebar />

      <main className="flex-1 ml-56 p-6 relative z-10">
        <header className="mb-6">
          <div className="flex items-center gap-2 mb-1">
            <Sparkles size={14} className="text-[#F59E0B]" />
            <span className="text-[10px] text-[#F59E0B] font-semibold uppercase tracking-wider">
              AI-Generated Insights
            </span>
          </div>
          <h1 className="text-xl font-bold">Insights</h1>
          <p className="text-xs text-[#8A8F98] mt-0.5">
            6 insights generated by MiMo V2.5 agents from your dataset
          </p>
        </header>

        {/* Insight cards */}
        <div className="space-y-4">
          {insights.map((insight, i) => {
            const config = typeConfig[insight.type] || typeConfig.anomaly;
            return (
              <div key={i} className={`glass p-5 insight-card ${config.class}`}>
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-[rgba(94,106,210,0.08)] flex items-center justify-center shrink-0">
                    {config.icon}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-1">
                      <span className="badge badge-info">{config.label}</span>
                      <span className="text-[10px] text-[#555566]">by {insight.agent} Agent</span>
                      <span className="ml-auto text-[10px] font-[family-name:var(--font-mono)] text-[#8A8F98]">
                        {insight.confidence}% confidence
                      </span>
                    </div>
                    <h3 className="font-semibold text-sm mb-1">{insight.title}</h3>
                    <p className="text-xs text-[#8A8F98] leading-relaxed">{insight.desc}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Summary */}
        <div className="glass p-5 mt-6">
          <h4 className="text-xs font-semibold mb-3">Executive Summary (Reporter Agent)</h4>
          <div className="text-xs text-[#8A8F98] leading-relaxed space-y-2">
            <p>
              <strong className="text-[#EDEDEF]">Overall Performance:</strong> Strong year with 18.2% revenue growth. Q4 showing
              exceptional momentum with holiday season driving record sales of $120K in December.
            </p>
            <p>
              <strong className="text-[#EDEDEF]">Key Risks:</strong> Cart abandonment spike on Oct 22 needs investigation.
              Clothing category declining (-8% MoM) requires attention before winter season.
            </p>
            <p>
              <strong className="text-[#EDEDEF]">Opportunities:</strong> Asia Pacific is the fastest-growing region (22.1%).
              Email campaigns show strong correlation with revenue — increase frequency recommended.
              Ad spend ROI is healthy with r=0.82 correlation to revenue.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
